// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyhirhsyquyysibeieas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5aGlyaHN5cXV5eXNpYmVpZWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4MDg2MzQsImV4cCI6MjA0OTM4NDYzNH0.atTogyzu8Eb40QgzyKUxRUPbJEP-h6bJnjqddYrGfRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);